spring:
  profiles:
    active: ${ACTIVE:default}

  application:
    name: auth

  reactor:
    context-propagation: auto

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  access:
    private-key: ${JWT_ACCESS_PRIVATE_KEY}
  refresh:
    private-key: ${JWT_REFRESH_PRIVATE_KEY}

google:
  oauth:
    uri: https://oauth2.googleapis.com
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect: ${GOOGLE_OAUTH_REDIRECT:http://localhost:3000}
